version: "3.9"
services:
  server:
    build: ./server
    ports:
    - "5000:5000"
    volumes:
      - ./server:/app
    environment:
      FLASK_ENV: development
  web:
    build: ./client
    command: npm start
    ports:
      - "80:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

